# -*- coding: utf-8 -*-
"""corrected_python .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRp6csTQ4UXhGVG2ElFsP7zvib3NyTXd
"""

PASS_MARK = 40

def calculate_average(marks):
    total = 0

    for m in marks:
        total = total + m

    return total / (len(marks))


def is_passing(mark):
    if mark >= PASS_MARK:
        return True

    return False


def get_grade(average):
    if average >= 90:
        return "First"

    elif average >= 60:
        return "Second"

    elif average >= 45:
        return "Distinction"

    return "Fail"

calculate_average([80,90,100])

!python test_student_utils.py